### ISSUE TITLE
Can't find download link of release aar file 

### ISSUE THREAD

**Issue by Digital2Slave** [steveliles/opencv-android-3.0.0#1]
Thanks a lot for your awesome job about building OpenCV aar file. I found your blog at [http://steveliles.github.io/building_opencv_as_an_aar_for_android.html](url) and bintray  [https://bintray.com/steveliles/maven/OpenCV-Android/3.1.0](url).
But, I find **No direct downloads selected for this package** at the bottom of [https://bintray.com/steveliles/maven/OpenCV-Android/3.1.0](url). 
And in this repo, I'm not find any release version for your opencv-android. Could you please put download link for opencv-android ?

**Comment by steveliles** [comment]
Hi,

You can always download directly from bintray from the [files section](https://bintray.com/steveliles/maven/OpenCV-Android/3.1.0#files/org/opencv/OpenCV-Android/3.1.0), but I've also now pinned the 3.1.0 artifacts on the main page for this lib.

**Comment by Digital2Slave** [comment]
@steveliles Thanks very much. I also found aar file in **C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.opencv\OpenCV-Android\3.1.0\8be6d3319027b84d379ca79d931755b421704b12** folder.
